general:
  seed: 42

data:
  dataset_to_use: "real"
  synthetic_dataset: "data/synthetic/dataset.parquet"
  real_dataset: "data/real/dataset.parquet"
  raw_data_path: "data/real/raw"
  index: "WIG20"
  n_samples: 500
  real_data_start: "2021-01-01"
  real_data_end: "2023-12-31"

  mask_config:
    ts_keep_prob: 0.2       #strong masking X_ts
    index_keep_prob: 0.5     #medium masking X_index
    static_p: 0.3          # weak masking X_static

model:
  name: "ConvReconstructionModel"

training:
  mode: "finetune"  # "train" or "finetune"
  pretrained_model_path: "models/conv_reconstruction_model.pt"
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "reduce_on_plateau"
  early_stopping_patience: 5
  save_best_model: true
  model_save_path: "models/conv_reconstruction_model2.pt"

loss:
  type: "composite"
  weights:
    mse: 1.0
    min_val: 0.3
    max_val: 0.3
    min_pos: 0.2
    max_pos: 0.2
    roughness: 0.1
    pull: 0.1
  adaptive_weighting: false