compute_metrics:
  input_path: data/synthetic/dataset.parquet
  output_path: results/metrics_report.json
  ts_keep_probs: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  index_keep_probs: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  metrics:
    - mse
    - mae
    - r2
  model_path: models/model.pt
  model:
    class_name: MaskedReconstructionModel
    module: src.models.masked_reconstruction_model
  date_range:
    use_date_range: false
    start: '2020-01-01'
    end: '2024-12-31'
  n_samples: 400
  random_seed: 42
  mask_config:
      ts_keep_prob: 0.2       #strong masking X_ts
      index_keep_prob: 0.5     #medium masking X_index
      static_keep_prob: 1.0         # no masking X_static

plot_samples:
  input_path: data/real/dataset.parquet
  n_samples: 6
  model_path: models/model.pt
  model:
    class_name: MaskedReconstructionModel
    module: src.models.masked_reconstruction_model
  date_range:
    use_date_range: true
    start: '2020-01-01'
    end: '2024-12-31'
  mask_config:
    ts_keep_prob: 0.1       # strong masking X_ts
    index_keep_prob: 1.0    # low masking X_index
    static_keep_prob: 1.0   # no masking X_static
  plot_config:
    rows: 2
    cols: 3
    show_y_pred: true
    show_true_visible: true
    show_true_masked: true
    show_x_index_visible: true

