generation:
  n_intervals: 60000  # 60 * 60 * 100
  time_interval: "1min"
  start_time: "2025-01-01 00:00:00"
  return_type: "log"
  output_path: "data/sample/dataset.parquet"

simulation:
  tick_values: [8]
  sigma_pairs:
    - [0.00004, 0.00008]
  correlations: [0.2, 0.5, 0.8]
