api:
  model:
    module: src.models.prior_correction_model
    class_name: PriorCorrectionModel
    model_path: models/prior_correction_model.pt
    kwargs:
      seq_len: 60
      static_dim: 10
      channels: 64
      n_blocks: 4
      dropout: 0.05
      correction_scale: 0.25

  input:
    static_features:
      - corr_30
      - corr_60
      - open_pos
      - close_pos
      - body_to_range
      - direction
      - index_open_pos
      - index_close_pos
      - index_body_to_range
      - index_direction
